#!/usr/bin/env bash
set -euo pipefail
MODE="${1:-live}"
RE='BOOT agent=v22.3-kiss-fast-reroute|KEY_STATE|IDENTITY_READY|HTTP_HELPER_READY|GEM_FILTER_ARMED|GEM_FILTER_FALLBACK|CAIRODRIVE_READY|SEARCH_INTERCEPT|SEARCH_FORWARD|CATEGORY_FORWARD|GOOGLE_REQUEST|GOOGLE_OK|AUTOCOMPLETE_|GOOGLE_TRAFFIC_|GOOGLE_SKIP|GOOGLE_BLOCKED|GOOGLE_HTTP|GOOGLE_NETWORK_ERROR|GOOGLE_PARSE_ERROR|HTTP_CANCEL|NATIVE_SEARCH_FALLBACK|NATIVE_SEARCH_FALLBACK_ERROR|NATIVE_INJECT|NATIVE_INJECT_ERROR|COMPLETE_ERROR|SEARCH_HANDLER_ERROR|PLACE_DETAILS_SELECT|PLACE_DETAILS_REQUEST|PLACE_DETAILS_OK|LANDMARK_DETAILS_ENRICHED|NAV_POINT_SELECTED|ARRIVAL_OPEN_CHECK|GEM_FILTER_ERROR|INSTALL_GEM_ERROR|FATAL EXCEPTION|ANR in |SIGSEGV|SIGABRT'
case "$MODE" in
  clear) adb logcat -c; echo "logcat cleared" ;;
  live) adb logcat -v time -s cairodrive:I AndroidRuntime:E ActivityManager:I | grep --line-buffered -E "$RE" ;;
  snapshot)
    tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
    adb logcat -d -b all -v time > "$tmp"
    echo '=== v22.3 SEARCH SNAPSHOT ==='
    grep -E "$RE" "$tmp" | tail -n 300 || true
    echo
    echo '=== COUNTS ==='
    for m in 'BOOT agent=v22.3-kiss-fast-reroute' 'KEY_STATE places=yes routes=yes' 'GEM_FILTER_ARMED' 'SEARCH_INTERCEPT kind=typed' 'SEARCH_INTERCEPT kind=category' 'AUTOCOMPLETE_REQUEST' 'AUTOCOMPLETE_OK' 'AUTOCOMPLETE_SELECT' 'AUTOCOMPLETE_PANEL_SHOW' 'GOOGLE_REQUEST' 'GOOGLE_OK' 'PLACE_DETAILS_SELECT' 'PLACE_DETAILS_OK' 'LANDMARK_DETAILS_ENRICHED' 'NAV_POINT_SELECTED' 'HTTP_CANCEL' 'NATIVE_INJECT kind=typed' 'NATIVE_INJECT kind=category' 'NATIVE_SEARCH_FALLBACK' 'GOOGLE_HTTP' 'GOOGLE_NETWORK_ERROR' 'FATAL EXCEPTION' 'ANR in ' 'SIGSEGV' 'SIGABRT'; do
      printf '%-42s %s\n' "$m" "$(grep -F -c "$m" "$tmp" || true)"
    done
    ;;
  *) echo "Usage: $0 {clear|live|snapshot}" >&2; exit 2 ;;
esac
