/* v24.2 Free Drive traffic: nearby Google traffic -> sparse Magic Lane native Paths.
 * No frame hook. Raster work stays on one Java worker. Only SLOW/JAM is rendered.
 */
const FREE_TRAFFIC_CHECK_MS=4000;
const FREE_TRAFFIC_MOVING_REFRESH_MS=75000;
const FREE_TRAFFIC_SLOW_REFRESH_MS=120000;
const FREE_TRAFFIC_TRANSIENT_RETRY_MS=15000;
const FREE_TRAFFIC_SESSION_RETRY_MS=5000;
const FREE_TRAFFIC_MAX_PATHS=36;
let __googleMapTilesKey='',__googleMapTilesKeyLoaded=false,__JTrafficVectorizer=null;
let __freeTrafficTimer=null,__freeTrafficBusy=false,__freeTrafficToken=null,__freeTrafficStartedAt=0,__freeTrafficRetryAt=0;
let __freeTrafficWindowKey='',__freeTrafficFingerprint='',__freeTrafficEntries=[],__freeTrafficTaskClass=null;
let __freeTrafficFollowing=false,__freeTrafficFollowCheckedAt=0,__freeTrafficZoom=16;
const __freeTrafficJobs=[];

function loadGoogleMapTilesKey(force=false){
  if(__googleMapTilesKeyLoaded&&!force)return !!__googleMapTilesKey;if(!Java.available)return false;
  try{Java.perform(()=>{const AT=Java.use('android.app.ActivityThread'),app=AT.currentApplication();if(!app)return;const prefs=app.getSharedPreferences('cairodrive_private',0);const staged=readStagedSecret('/data/local/tmp/gtk'),saved=String(prefs.getString('google_map_tiles_key','')||'').trim();if(staged)prefs.edit().putString('google_map_tiles_key',staged).apply();if(staged&&staged!==__googleMapTilesKey)__freeTrafficRetryAt=0;__googleMapTilesKey=staged||saved;__googleMapTilesKeyLoaded=true;log(`GOOGLE_TILE_KEY_STATE present=${__googleMapTilesKey?'yes':'no'} storage=private-prefs`);});}catch(e){log(`GOOGLE_TILE_KEY_ERROR ${String(e)}`);}return !!__googleMapTilesKey;
}
function ensureTrafficVectorizer(){if(__JTrafficVectorizer)return __JTrafficVectorizer;if(!Java.available)return null;try{Java.perform(()=>{__JTrafficVectorizer=Java.use('com.cairodrive.traffic.GoogleTrafficTileVectorizer');});}catch(e){log(`FREE_TRAFFIC_HELPER_ERROR ${String(e)}`);__JTrafficVectorizer=null;}return __JTrafficVectorizer;}
function freeTrafficAppForeground(){let fg=true;if(!Java.available)return true;try{Java.perform(()=>{const Info=Java.use('android.app.ActivityManager$RunningAppProcessInfo'),AM=Java.use('android.app.ActivityManager'),i=Info.$new();AM.getMyMemoryState(i);fg=Number(i.importance.value)<=200;});}catch(_){fg=true;}return fg;}
function freeTrafficLocation(){let loc=null;try{Java.perform(()=>{const AT=Java.use('android.app.ActivityThread'),app=AT.currentApplication();if(app)loc=bestLocalLocation(app.getApplicationContext());});}catch(_){}if(!loc||!Number.isFinite(loc.latitude)||!Number.isFinite(loc.longitude)||Number(loc.accuracy)>75||Date.now()-Number(loc.time)>30000)return null;return loc;}
function freeTrafficSelectZoom(speed){const s=Number(speed);if(__freeTrafficZoom===16&&Number.isFinite(s)&&s>=24)__freeTrafficZoom=15;else if(__freeTrafficZoom===15&&(!Number.isFinite(s)||s<=19))__freeTrafficZoom=16;return __freeTrafficZoom;}
function freeTrafficWindowKey(loc,z){const n=2**z,lat=Math.max(-85.05112878,Math.min(85.05112878,Number(loc.latitude))),lon=((Number(loc.longitude)+180)%360+360)%360-180,r=lat*Math.PI/180,x=Math.max(0,Math.min(n-1,Math.floor((lon+180)/360*n))),merc=Math.log(Math.tan(r)+1/Math.cos(r)),y=Math.max(0,Math.min(n-1,Math.floor((1-merc/Math.PI)/2*n))),speed=Number(loc&&loc.speed),bearing=Number(loc&&loc.bearing),moving=Number.isFinite(speed)&&speed>=4&&Number.isFinite(bearing),sector=moving?Math.floor((((bearing%360)+360)%360+45)%360/90):4;return `${z}/${x}/${y}/${sector}`;}
function startFreeTrafficVectorization(loc,z){const H=ensureTrafficVectorizer();if(!H||!resolveIdentity())return null;let token=null;try{Java.perform(()=>{token=String(H.start(String(__googleMapTilesKey),String(ANDROID_PACKAGE),String(ANDROID_CERT_SHA1),Number(loc.latitude),Number(loc.longitude),Number.isFinite(Number(loc.bearing))?Number(loc.bearing):NaN,Number.isFinite(Number(loc.speed))?Number(loc.speed):0,Number(z),CONNECT_TIMEOUT_MS,6500));});}catch(e){log(`FREE_TRAFFIC_START_ERROR ${String(e)}`);}return token;}
function pollFreeTrafficVectorization(token){if(!token||!__JTrafficVectorizer)return null;let out=null;try{Java.perform(()=>{const r=__JTrafficVectorizer.poll(Number(token));if(r!==null)out=String(r);});}catch(e){return {done:true,error:String(e)};}if(out===null)return {done:false};if(out==='CANCELLED')return {done:true,cancelled:true};if(out.startsWith('ERR:'))return {done:true,error:out.slice(4)};if(out.startsWith('OK:'))return {done:true,body:out.slice(3)};return {done:true,error:'bad-vectorizer-response'};}
function cancelFreeTrafficVectorization(){if(!__freeTrafficToken||!__JTrafficVectorizer)return;try{Java.perform(()=>__JTrafficVectorizer.cancel(Number(__freeTrafficToken)));}catch(_){}__freeTrafficToken=null;}
function releaseFreeTrafficEntries(collection){for(const e of __freeTrafficEntries){try{if(collection&&e.path)collection.remove(e.path);}catch(_){}try{if(e.path&&e.path.$dispose)e.path.$dispose();}catch(_){}}__freeTrafficEntries=[];__freeTrafficFingerprint='';}
function clearFreeTrafficOnGemThread(reason='clear'){const c=getRealTrafficPathCollection();releaseFreeTrafficEntries(c);if(reason!=='refresh')log(`FREE_TRAFFIC_CLEARED reason=${reason}`);}
function freeMagicCoordinate(lat,lon){const C=Java.use('com.magiclane.sdk.places.Coordinates'),o=C.$new();o.setLatitude(Number(lat));o.setLongitude(Number(lon));return o;}
function createFreeTrafficPath(segment,index){const ArrayList=Java.use('java.util.ArrayList'),PathCls=Java.use('com.magiclane.sdk.core.Path'),list=ArrayList.$new();for(const c of segment.coords||[])list.add(freeMagicCoordinate(c.latitude,c.longitude));let path=null;try{path=PathCls.Companion.value.produceWithCoords(list);}catch(e){log(`FREE_TRAFFIC_PATH_CREATE_ERROR ${String(e)}`);}if(path)try{path.setName(`__cairodrive_free_traffic_${index}_${String(segment.speed).toLowerCase()}`);}catch(_){}return path;}
function renderFreeTrafficOnGemThread(payload){if(!payload||!Array.isArray(payload.segments))return;const c=getRealTrafficPathCollection();if(!c)return;if(payload.fingerprint===__freeTrafficFingerprint)return;releaseFreeTrafficEntries(c);const next=[];let failed=0;for(let i=0;i<payload.segments.length&&i<FREE_TRAFFIC_MAX_PATHS;i++){const s=payload.segments[i],p=createFreeTrafficPath(s,i);if(!p){failed++;continue;}if(addTrafficNativePath(c,p,s.speed))next.push({path:Java.retain(p)});else{try{if(p.$dispose)p.$dispose();}catch(_){}failed++;}}__freeTrafficEntries=next;if(next.length)__freeTrafficFingerprint=payload.fingerprint;log(`FREE_TRAFFIC_RENDERED paths=${next.length} failed=${failed} renderer=MagicLane-native source=Google-layerTraffic-raster-vector`);}
function probeFreeTrafficFollowOnGemThread(){try{const mv=__trafficMapSurface&&__trafficMapSurface.getMapView?__trafficMapSurface.getMapView():null;__freeTrafficFollowing=!!(mv&&mv.isFollowingPosition());}catch(_){__freeTrafficFollowing=false;}__freeTrafficFollowCheckedAt=Date.now();}
function ensureFreeTrafficTaskClass(){if(__freeTrafficTaskClass)return __freeTrafficTaskClass;const Function0=Java.use('kotlin.jvm.functions.Function0');__freeTrafficTaskClass=Java.registerClass({name:`com.cairodrive.runtime.FreeTrafficTask${Process.id}`,implements:[Function0],methods:{invoke(){const j=__freeTrafficJobs.shift();if(!j)return null;try{if(j.kind==='render')renderFreeTrafficOnGemThread(j.payload);else if(j.kind==='probe')probeFreeTrafficFollowOnGemThread();else clearFreeTrafficOnGemThread(j.reason);}catch(e){log(`FREE_TRAFFIC_GEM_ERROR ${String(e)}`);}return null;}}});return __freeTrafficTaskClass;}
function postFreeTrafficJob(job){if(!Java.available)return false;__freeTrafficJobs.splice(0,__freeTrafficJobs.length);__freeTrafficJobs.push(job);try{Java.perform(()=>{const Task=ensureFreeTrafficTaskClass(),task=Task.$new();let posted=false;for(const cls of ['com.magiclane.sdk.util.GemCall','com.magiclane.sdk.util.SdkCall'])try{const G=Java.use(cls);if(G.execute){G.execute(task);posted=true;break;}}catch(_){}if(!posted){__freeTrafficJobs.splice(0,__freeTrafficJobs.length);log('FREE_TRAFFIC_GEM_POST_FAILED failOpen=yes');}});return true;}catch(_){__freeTrafficJobs.splice(0,__freeTrafficJobs.length);return false;}}
function parseFreeTrafficResult(body){const d=JSON.parse(String(body||'{}')),out=[];for(const s of Array.isArray(d.segments)?d.segments:[]){const coords=[];for(const q of Array.isArray(s.coords)?s.coords:[]){if(!Array.isArray(q)||q.length<2)continue;const lat=Number(q[0]),lon=Number(q[1]);if(Number.isFinite(lat)&&Number.isFinite(lon))coords.push({latitude:lat,longitude:lon});}if(coords.length>=2)out.push({speed:String(s.speed)==='TRAFFIC_JAM'?'TRAFFIC_JAM':'SLOW',lengthM:Number(s.lengthM)||0,coords});}return {segments:out,z:Number(d.z),tileCount:Number(d.tileCount)||0,fetched:Number(d.fetched)||0,cached:Number(d.cached)||0};}
function freeTrafficFingerprint(segs){return (segs||[]).map(s=>`${s.speed}:${trafficGeometryHash(s.coords)}`).join('|');}
function freeTrafficRetryDelay(error){const s=String(error||'').toLowerCase();if(s.includes('forbidden'))return 300000;if(s.includes('quota')||s.includes('provider cooldown'))return 180000;if(s.includes('session invalid'))return FREE_TRAFFIC_SESSION_RETRY_MS;return FREE_TRAFFIC_TRANSIENT_RETRY_MS;}
async function freeTrafficTick(){if(__freeTrafficBusy)return;__freeTrafficBusy=true;try{const now=Date.now();if(__navSession){cancelFreeTrafficVectorization();if(__freeTrafficEntries.length)postFreeTrafficJob({kind:'clear',reason:'navigation-active'});return;}if(!freeTrafficAppForeground()||!androidNetworkAvailable()||!loadGoogleMapTilesKey()||now<__freeTrafficRetryAt)return;if(!__trafficMapSurface){discoverTrafficMapSurface('free-drive');return;}if(now-__freeTrafficFollowCheckedAt>5000){postFreeTrafficJob({kind:'probe'});return;}if(!__freeTrafficFollowing){if(__freeTrafficEntries.length)postFreeTrafficJob({kind:'clear',reason:'not-following-position'});return;}const loc=freeTrafficLocation();if(!loc)return;const speed=Number(loc.speed),z=freeTrafficSelectZoom(speed),wk=freeTrafficWindowKey(loc,z),refresh=Number.isFinite(speed)&&speed>=4?FREE_TRAFFIC_MOVING_REFRESH_MS:FREE_TRAFFIC_SLOW_REFRESH_MS;if(__freeTrafficToken)return;if(wk===__freeTrafficWindowKey&&now-__freeTrafficStartedAt<refresh)return;__freeTrafficWindowKey=wk;__freeTrafficStartedAt=now;const token=startFreeTrafficVectorization(loc,z);if(!token){__freeTrafficRetryAt=Date.now()+FREE_TRAFFIC_TRANSIENT_RETRY_MS;return;}__freeTrafficToken=token;const result=await new Promise(resolve=>{const tick=()=>{const r=pollFreeTrafficVectorization(token);if(!r||!r.done){setTimeout(tick,150);return;}resolve(r);};tick();});if(__freeTrafficToken===token)__freeTrafficToken=null;if(__navSession)return;if(result.cancelled)return;if(result.error){const delay=freeTrafficRetryDelay(result.error);__freeTrafficRetryAt=Date.now()+delay;__freeTrafficStartedAt=0;log(`FREE_TRAFFIC_ERROR retryMs=${delay} ${String(result.error).slice(0,160)}`);return;}__freeTrafficRetryAt=0;const parsed=parseFreeTrafficResult(result.body),fp=freeTrafficFingerprint(parsed.segments);if(fp===__freeTrafficFingerprint)return;if(!parsed.segments.length){if(__freeTrafficEntries.length)postFreeTrafficJob({kind:'clear',reason:'no-congestion'});return;}postFreeTrafficJob({kind:'render',payload:{segments:parsed.segments.slice(0,FREE_TRAFFIC_MAX_PATHS),fingerprint:fp}});log(`FREE_TRAFFIC_UPDATE segments=${parsed.segments.length} tiles=${parsed.tileCount} fetched=${parsed.fetched} cached=${parsed.cached} z=${parsed.z}`);}catch(e){__freeTrafficRetryAt=Date.now()+FREE_TRAFFIC_TRANSIENT_RETRY_MS;log(`FREE_TRAFFIC_TICK_ERROR ${String(e)}`);}finally{__freeTrafficBusy=false;}}
function startFreeDriveTraffic(){if(__freeTrafficTimer)return;loadGoogleMapTilesKey(true);ensureTrafficVectorizer();__freeTrafficTimer=setInterval(()=>{freeTrafficTick();},FREE_TRAFFIC_CHECK_MS);setTimeout(()=>freeTrafficTick(),1200);log(`FREE_TRAFFIC_READY source=Google-layerTraffic-raster-vector maxPaths=${FREE_TRAFFIC_MAX_PATHS} nearbyWindow=6-moving/9-slow nativePaths=yes followOnly=yes zoomHysteresis=yes`);}
